# fly.toml app configuration file generated for virexa-video on 2026-08-24T19:31:34+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'virexa-video'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  WHISPER_METHOD = 'none'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  ports = []

[[vm]]
  size = 'performance-2x'
  memory = '4gb'
