# fly.toml app configuration file generated for virexa-windmill-worker on 2026-08-24T19:28:48+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'virexa-windmill-worker'
primary_region = 'sin'

[build]
  image = 'ghcr.io/windmill-labs/windmill:latest'

[deploy]
  strategy = 'rolling'

[env]
  MODE = 'worker'
  NUM_WORKERS = '4'
  SLEEP_QUEUE = '1000'
  WORKER_GROUP = 'general'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2gb'
