"""initial business schema

Revision ID: 822226577a23
Revises: 
Create Date: 2026-08-24 17:38:43.805045
"""
from __future__ import annotations

from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa

revision = '822226577a23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_time', 'audit_events', ['created_at'], unique=False)
    op.create_table('brands',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('niche', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiments',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('dimension', sa.String(length=48), nullable=False),
    sa.Column('variant_a', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variant_b', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_interaction_id', sa.String(length=255), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('author_handle', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_interaction_id', name='uq_interaction_platform')
    )
    op.create_index('ix_interactions_created', 'interactions', ['created_at'], unique=False)
    op.create_table('learning_patterns',
    sa.Column('dimension', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('mean_performance', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension', 'value', name='uq_learning_dimension_value')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_system_setting_key')
    )
    op.create_table('leads',
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('handle', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engagement', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trend', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'source', 'source_id', name='uq_opportunity_source')
    )
    op.create_index('ix_opportunities_brand_created', 'opportunities', ['brand_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_opportunities_dedup_hash'), 'opportunities', ['dedup_hash'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'platform', 'handle', name='uq_platform_account')
    )
    op.create_table('responses',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('sent_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('platform_reply_id', sa.String(length=255), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interaction_id', name='uq_response_interaction')
    )
    op.create_table('content_items',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('state_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'dedup_hash', name='uq_content_dedup')
    )
    op.create_index('ix_content_state_created', 'content_items', ['state', 'created_at'], unique=False)
    op.create_table('opportunity_scores',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('penalties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('scored_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total BETWEEN 0 AND 100', name='ck_score_total_range'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'version', name='uq_score_version')
    )
    op.create_table('platform_connections',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_app_id', sa.String(length=200), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_ref', sa.String(length=255), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_items',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('depth', sa.String(length=32), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'depth', name='uq_research_depth')
    )
    op.create_table('cost_events',
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=128), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_events_day', 'cost_events', ['created_at'], unique=False)
    op.create_table('platform_variants',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'platform', name='uq_variant_platform')
    )
    op.create_table('qc_results',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold_auto', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('threshold_review', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'attempt', name='uq_qc_attempt')
    )
    op.create_table('research_sources',
    sa.Column('research_item_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('untrusted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_item_id'], ['research_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_queue',
    sa.Column('content_item_id', sa.UUID(), nullable=True),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolution', sa.String(length=24), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_queue_status', 'review_queue', ['status'], unique=False)
    op.create_table('script_versions',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('fact_check', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'version', name='uq_script_version')
    )
    op.create_table('scripts',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', name='uq_script_current')
    )
    op.create_table('strategies',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('objective', sa.String(length=64), nullable=False),
    sa.Column('platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', name='uq_strategy_content')
    )
    op.create_table('publish_jobs',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('remote_url', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['platform_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'idempotency_key', name='uq_publish_idempotency')
    )
    op.create_index('ix_publish_jobs_status', 'publish_jobs', ['status'], unique=False)
    op.create_table('video_jobs',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('script_version_id', sa.UUID(), nullable=True),
    sa.Column('mpt_task_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_jobs_mpt_task_id'), 'video_jobs', ['mpt_task_id'], unique=False)
    op.create_index('ix_video_jobs_status', 'video_jobs', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('size_bytes', sa.Numeric(precision=20, scale=0), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('video_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['video_job_id'], ['video_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_content_type', 'assets', ['content_item_id', 'asset_type'], unique=False)
    op.create_table('published_posts',
    sa.Column('publish_job_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('remote_url', sa.Text(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['publish_job_id'], ['publish_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_post_id', name='uq_published_post')
    )
    op.create_table('metric_snapshots',
    sa.Column('published_post_id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('published_post_id', 'captured_at', 'metric_key', name='uq_metric_snapshot')
    )
    op.create_index('ix_metric_snapshots_key_time', 'metric_snapshots', ['metric_key', 'captured_at'], unique=False)
    op.create_table('performance_scores',
    sa.Column('published_post_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('published_post_id', name='uq_performance_post')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_scores')
    op.drop_index('ix_metric_snapshots_key_time', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_table('published_posts')
    op.drop_index('ix_assets_content_type', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_video_jobs_status', table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_mpt_task_id'), table_name='video_jobs')
    op.drop_table('video_jobs')
    op.drop_index('ix_publish_jobs_status', table_name='publish_jobs')
    op.drop_table('publish_jobs')
    op.drop_table('strategies')
    op.drop_table('scripts')
    op.drop_table('script_versions')
    op.drop_index('ix_review_queue_status', table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_table('research_sources')
    op.drop_table('qc_results')
    op.drop_table('platform_variants')
    op.drop_index('ix_cost_events_day', table_name='cost_events')
    op.drop_table('cost_events')
    op.drop_table('research_items')
    op.drop_table('platform_connections')
    op.drop_table('opportunity_scores')
    op.drop_index('ix_content_state_created', table_name='content_items')
    op.drop_table('content_items')
    op.drop_table('responses')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_opportunities_dedup_hash'), table_name='opportunities')
    op.drop_index('ix_opportunities_brand_created', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('leads')
    op.drop_table('system_settings')
    op.drop_table('learning_patterns')
    op.drop_index('ix_interactions_created', table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('experiments')
    op.drop_table('brands')
    op.drop_index('ix_audit_events_time', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
